### PR TITLE
Implement MovIntToFloat, MovFloatToInt for s390.

### PR DESCRIPTION
**Pull request by mcornac**

### CODE REVIEW

**Comment by thinkingdust** [comment]
I implemented Joran's suggestions in https://github.com/andrewlow/v8z/pull/17 to get rid of store followed by load from same location.

**Comment by joransiu** [comment]
Thanks @thinkingdust.  lgtm

**Comment by thinkingdust** [comment]
Rebased to fix conflicts.

**Comment by john-yan** [comment]
@joransiu Could you plz explain why shift is used before ldgr?

**Comment by joransiu** [comment]
@john-yan, because a 32-bit float is stored in the upper 32-bits of a FPR.

**Pull request merged**
